### ISSUE TITLE
Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.

### ISSUE THREAD

**Issue by zhLawliet** [alexlee-gk/lpips-tensorflow#1]
my  producer_version = default_graph.graph_def_versions.producer is 24
so i need ti download the  ['net-lin_alex_v0.1_24.pb', 'net-lin_alex_v0.1.pb'], but there is not net-lin_alex_v0.1_24.pb. how can i get it?

when i run the test_network.py, there are errors:

2018-12-26 11:00:51.189078: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: import/Cast_10 = Cast[DstT=DT_INT64, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/Shape_53). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: import/Cast_10 = Cast[DstT=DT_INT64, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/Shape_53)]]
2018-12-26 11:00:51.194640: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: import/Cast_10 = Cast[DstT=DT_INT64, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/Shape_53). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: import/Cast_10 = Cast[DstT=DT_INT64, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/Shape_53)]]
Traceback (most recent call last):
  File "/home/zhang/anaconda2/envs/HDR/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/zhang/anaconda2/envs/HDR/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/zhang/anaconda2/envs/HDR/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: import/Cast_10 = Cast[DstT=DT_INT64, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/Shape_53). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: import/Cast_10 = Cast[DstT=DT_INT64, SrcT=DT_INT32, Truncate=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/Shape_53)]]

**Comment by alexlee-gk** [comment]
I only exported versions 26 and 27. You can export the model by following the instructions at the end of the README, that way it will use the producer version of your dependencies.

However, I'm not sure if onnx-tensorflow supports producer versions that old. Currently, onnx-tensorflow supports tensorflow>=1.5.0.
